export const prefixes = [
  "Al",
  "Be",
  "Ca",
  "De",
  "El",
  "Fa",
  "Ga",
  "He",
  "Ig",
  "Jo",
  "Ke",
  "La",
  "Ma",
  "No",
  "Or",
  "Pa",
  "Qu",
  "Re",
  "Si",
  "To",
  "Ul",
  "Va",
  "Wi",
  "Xa",
  "Yo",
  "Ze",
];

export const suffixes = [
  "bar",
  "dox",
  "fer",
  "gal",
  "hax",
  "jox",
  "kas",
  "lim",
  "mox",
  "nox",
  "pax",
  "quix",
  "rax",
  "sax",
  "tax",
  "vex",
  "wax",
  "yox",
  "zax",
];

export const classes = [
  "Artefice",
  "Barbaro",
  "Bardo",
  "Chierico",
  "Druido",
  "Ladro",
  "Stregone",
  "Mago",
  "Warlock",
  "Ranger",
  "Guerriero",
];

export const titles = [
  "Arci Duca del Glitter",
  "Cardinale degli Unicorni",
  "Ammiraglio dei Narvali",
  "Regina del Drag",
  "Duca del Sodo",
  "Duchessa dei Reality",
  "Contessa del Sesso senza Impegni",
  "Accolito dell'Arcobaleno",
  "Regina delle Paillettes",
  "Marchesa dell'Orgoglio Lesbo",
  "Duca del Feticismo Sessuale",
  "Gran Plissé della Trans-Silvana",
  "Cavaliere dell'Ultima Pinta Aperta sul Tavolo Giustifictrice di Etero Confusi",
  "Alta Passera",
  "Cavaliere dello Sfarzo",
  "Mastro Discotecaro",
  "Maestra dei Carri",
  "Protettrice dei pronomi neutri",
  "Ciambellano del Pride",
  "Seguace di San Raffaella da Carrà",
  "Ranger del Battuage Selvaggio",
  "SEO manager",
  "Business Analyst",
  "il Bibliotecario",
  "Conquistatore di Gender",
  "Accolito della Lobby",
  "Eroe della Lobby",
  "il Multicolore",
  "la Dottoressa",
  "Fuoricorso",
  "Content Creator",
  "TikToker",
  "ArcoBalengo",
  "Arcontebaleno",
  "Gay delle Steppe",
  "Terrore dei Salotti",
  "Drago dei Contest",
  "Sindaco di Lanzo Torinese",
  "GranMaresciallo di Lgbilterra",
  "Re della Sauna",
];

export const preferences = [
  "Etero",
  "Gay",
  "Lesbica",
  "Bisessuale",
  "Pansessuale",
  "Asessuale",
  "Sapiosessuale",
  "PoliAmoroso",
  "PoliSessuale",
  "Queer",
];

export const races = [
  {
    label: "Human",
    images: [
      "human1.jpg",
      "human2.jpg",
      "human3.jpg",
      "human4.jpg",
      "human5.jpg",
      "human6.jpg",
      "human7.jpg",
      "human7.png",
    ],
  },
  {
    label: "Dragonborn",
    images: ["dragonborn1.png", "dragonborn2.png", "dragonborn3.png"],
  },
  {
    label: "Tiefling",
    images: ["human1.jpg"],
  },
  {
    label: "Dwarf",
    images: ["dwarf1.jpg"],
  },
  {
    label: "Elf",
    images: [
      "elf1.jpg",
      "elf2.jpg",
      "elf3.jpg",
      "elf4.jpg",
      "elf5.jpg",
      "elf6.jpg",
      "elf7.jpg",
    ],
  },
  {
    label: "Half-elf",
    images: [
      "human1.jpg",
      "human2.jpg",
      "human3.jpg",
      "human4.jpg",
      "human5.jpg",
      "human6.jpg",
      "human7.jpg",
      "human7.png",
      "halfelf1.jpg",
      "halfelf2.jpg",
      "halfelf3.jpg",
    ],
  },
  {
    label: "Half-Orc",
    images: ["human1.jpg", "human2.jpg"],
  },
  {
    label: "Gnome",
    images: ["halfling1.jpg", "halfling2.jpg", "halfelf1.jpg", "halfelf2.jpg"],
  },
];
