export const titles = [
  { label: "Marchesə" },
  { label: "Contə" },
  { label: "Arciducə" },
  { label: "Sindaco" },
  { label: "Protettore" },
  { label: "Re" },
  { label: "Regina" },
  { label: "Duca" },
  { label: "Terrore" },
  { label: "Distruttore" },
  { label: "Salvatore" },
  { label: "Gran Plissè" },
  { label: "Seguace" },
  { label: "Alto Cardinale" },
  { label: "Gran Sacerdotə" },
  { label: "Cavaliere" },
  { label: "Maestrə" },
  { label: "Ciambellanə" },
  { label: "Siniscalcə" },
  { label: "Maraja" },
  { label: "dell'Ordine" },
  { label: "Content Creator", alone: true },
  { label: "Alta Passera", alone: true },
  { label: "il Multicolore", alone: true },
  { label: "il Dottore", alone: true },
  { label: "Fuoricorso", alone: true },
  { label: "TikToker", alone: true },
  { label: "l'ArcoBalengo", alone: true },
  { label: "l'Arcontebaleno", alone: true },
  { label: "Bibliotecaro", alone: true },
  { label: "Fortunato", alone: true },
  { label: "Fortunadrago", alone: true },
  { label: "la Rossa", alone: true },
  { label: "SEO Manager", alone: true },
  { label: "Radiosə", alone: true },
  { label: "Business Analyst", alone: true },
  { label: "Ammiragliə dei Narvali", alone: true },
];

export const definitions = [
  "dei Salotti",
  "dei Contest",
  "di Lgbilterra",
  "di Lanzo Torinese",
  "della Sauna",
  "del Pride",
  "de Pronom Neutr",
  "dei Lumini",
  "della Lobby",
  "del Gender",
  "del Glitter",
  "dell'Arcobaleno",
  "delle Paillettes",
  "del Sesso senza Impegni",
  "del Battuage Selvaggio",
  "dello Sfarzo",
  "della Trans-silvana",
  "di Lesbo",
  "dell'Ultima Pinta Aperta sul Tavolo Giustifictrice di Etero Confusi",
  "di Santa Raffaella da Carrà",
  "della Disco",
  "degli Unicorni",
  "di Casarcobaleno",
  "del Carro d'Avanguarda del Pride",
];
